#!/usr/bin/env bash
# This script reads the /etc/passwd file and outputs the information for each user 
# in a specific storytelling format using the while loop and IFS.

# The /etc/passwd file structure is: 
# F1:Username:F2:Password:F3:UID:F4:GID:F5:GECOS:F6:HomeDirectory:F7:Shell

# Set IFS to colon (:) to split the line into the 7 expected fields.
while IFS=: read -r F1 F2 F3 F4 F5 F6 F7; do
    
    # Construct the output sentence following the required format.
    # All variables are used: F1 (Username), F4 (GID), F6 (Home Dir), F7 (Shell), 
    # F3 (UID), F2 (Password), F5 (GECOS/User Info).
    
    echo "The user ${F1} is part of the ${F4} gang, lives in ${F6} and rides ${F7}. ${F3}'s place is protected by the passcode ${F2}, more info about the user here: ${F5}"

done < /etc/passwd
