#!/usr/bin/env bash
#sada
a=1
while [ $a -le 10 ]
do	
    if [$i -qe 4]; then
        echo "bad luck"
    elif [$i -qe 8]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    a=$((a + 1))
done
